*TEDS 2016 indq.
*ESC Assistants training.

DATASET ACTIVATE 資料集1.
FREQUENCIES VARIABLES=C1
  /ORDER=ANALYSIS.

COMPUTE Ma=C1.
RECODE C1 (95 96 97 98=99) (ELSE=COPY).
VALUE LABELS MA  1 "Strongly Agree" 2 "Agree" 3 "Disagree" 4 "Strongly Disagree" 99 "Don't know".
FREQUENCIES Ma.
CROSSTABS
  /TABLES=Sex Age BY Ma
  /FORMAT=AVALUE TABLES
  /CELLS=COUNT ROW 
  /COUNT ROUND CELL.

CROSSTABS
  /TABLES=Age BY Ma
  /FORMAT=AVALUE TABLES
  /STATISTICS=CHISQ 
  /CELLS=COUNT ROW 
  /COUNT ROUND CELL.
